compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@nuxt/components@*":
    dependencies:
      consola: "*"
  css-loader@*:
    dependencies:
      webpack: ^4.27.0
  eslint-config-prettier@*:
    dependencies:
      eslint: ">=7.0.0"
  postcss-loader@*:
    dependencies:
      webpack: ^4.0.0
  vue-i18n@*:
    dependencies:
      vue: ^2

yarnPath: .yarn/releases/yarn-4.0.2.cjs
