nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  '@nuxt/components@*':
    dependencies:
      consola: '*'
  css-loader@*:
    dependencies:
      webpack: ^4.27.0
  eslint-config-prettier@*:
    dependencies:
      eslint: '>=7.0.0'
  postcss-loader@*:
    dependencies:
      webpack: ^4.0.0
  vue-i18n@*:
    dependencies:
      vue: ^2
