nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  'css-loader@*':
    dependencies:
      'webpack': '^4.27.0'
  'postcss-loader@*':
    dependencies:
      'webpack': '^4.0.0'
  'eslint-config-prettier@*':
    dependencies:
      'eslint': '>=7.0.0'
  'vue-i18n@*':
    dependencies:
      'vue': '^2'
  '@nuxt/components@*':
    dependencies:
      'consola': '*'
